" Set leader key
let mapleader = " "

" Reselect visual selection after indenting.
vnoremap < <gv
vnoremap > >gv

" Maintain the cursor position when yanking a visual selection.
vnoremap y myy`y

" Disable annoying command line typo.
nnoremap q: :q<CR>

" Save me!!
inoremap jj <Esc>:w<CR>

" Close buffer
nnoremap <Leader>q :q<CR>

" Save buffer
nnoremap <Leader>w :w<CR>

" Paste replace visual selection without copying it.
vnoremap p "_dP

" Easy insertion of a trailing ; or , from normal mode.
nnoremap ;; A;<Esc>
nnoremap ,, A,<Esc>

" Quickly clear search highlighting.
nnoremap <Leader>k :nohlsearch<CR>

" Move lines up and down.
inoremap <A-j> <Esc>:move .+1<CR>==gi
inoremap <A-k> <Esc>:move .-2<CR>==gi
nnoremap <A-j> :move .+1<CR>==
nnoremap <A-k> :move .-2<CR>==
vnoremap <A-j> :move '>+1<CR>gv=gv
vnoremap <A-k> :move '<-2<CR>gv=gv

" Window navigation
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-l> <C-w><C-l>
nnoremap <C-h> <C-w><C-h>


